//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamesShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class GenreGame
    {
        public int IDGenreGames { get; set; }
        public int idgenre { get; set; }
        public int idgame { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual Genre Genre { get; set; }
    }
}
