//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamesShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int IDReceipt { get; set; }
        public int iduser { get; set; }
        public int idgame { get; set; }
        public int idkey { get; set; }
        public Nullable<System.DateTime> DataBuying { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual Key Key { get; set; }
        public virtual User User { get; set; }
    }
}
